# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - '*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dotnet tool
      run: dotnet tool install -g dotnetCampus.TagToVersion
    - name: Set tag to version  
      run: dotnet TagToVersion -t ${{ github.ref }}
    - name: Store tag version for later
      run: echo "tagversion=$(dotnet TagToVersion -c -t ${{ github.ref }})" >> "$GITHUB_ENV"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release ./gaseous-signature-parser/gaseous-signature-parser.csproj
    - name: nuget pack
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} ./gaseous-signature-parser/gaseous-signature-parser.csproj
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg
  
  deploy_release:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Sign in to Nuget
        run: dotnet nuget add source --username michael-j-green --password ${{ secrets.NUGETKEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/gaseous-project/index.json"
      - name: Push to GitHub Package Registry
        run: dotnet nuget push "${{ env.NuGetDirectory }}/*.nupkg" --api-key ${{ secrets.NUGETKEY }} --source "github" --skip-duplicate 
      - name: Push to NuGet
        run: dotnet nuget push "${{ env.NuGetDirectory }}/*.nupkg" --api-key ${{secrets.NUGETPUBLISHKEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate